<?php
$title = 'Search';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'search')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;
echo $this->formRow($form->get('artist')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

?>
<div class="container-fluid">
    <div class="row-fluid">
        <div>
            <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <th>id</th>
                    <th>artist</th>
                    <th>title</th>
                    <th>&nbsp;</th>
                </tr>
                <?php foreach($this->albums as $album) : ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($album->id);?></td>
                        <td><?php echo $this->escapeHtml($album->artist);?></td>
                        <td><?php echo $this->escapeHtml($album->title);?></td>
             
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
</div>
